// <auto-generated />
namespace Sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class iitaldbcreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(iitaldbcreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202003310659239_iitaldbcreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
